# Generated by Django 3.2.12 on 2022-11-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='releaseDate',
            new_name='release_date',
        ),
    ]
