# Generated by Django 3.2.12 on 2022-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, unique=True)),
                ('social_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['stage_name'],
            },
        ),
    ]
