# Generated by Django 3.2.12 on 2022-11-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['stage_name']},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='socialLink',
            new_name='social_link',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='stageName',
            new_name='stage_name',
        ),
    ]
